#!/bin/bash
# A script that build uboot for rpi-zero

RED="\033[31;1m"
GREEN="\033[32;1m"
END="\033[0m"

DOCKER_IMAGE="cong2021/uboot"
CONTAINER_NAME="uboot_env"
CROSS_COMPILE="arm-linux-gnueabi-"
UBOOT_PATH=`pwd`
MOUNT_DIR="/work"

usage(){
    cat <<EOF
Usage: $1 options
-h, --help                  Show usage.
-i, --init                  Check dependency.
-u, --update                Update docker image.
[COMMON]                    Common that will run in docker.
EOF
}

__init(){
    docker --version > /dev/null
    if [ $? != 0 ]
    then
        echo -e ${RED}"Please install docker."${END}
        exit -1
    fi

    docker images|grep ${DOCKER_IMAGE} > /dev/null
    if [ $? != 0 ]
    then
        echo -e ${GREEN}"Docker image ${DOCKER_IMAGE} do not exist."
        echo -e "Pull ..."${END}
        docker pull ${DOCKER_IMAGE}
    fi
}

__update(){
    docker pull ${DOCKER_IMAGE}
}

main(){
    __init

    docker ps -a |grep ${CONTAINER_NAME} > /dev/null
    if [ $? == 0 ]
    then
        docker rm ${CONTAINER_NAME}
    fi

    docker run -it -v ${UBOOT_PATH}:${MOUNT_DIR} -w ${MOUNT_DIR} -e CROSS_COMPILE="${CROSS_COMPILE}" --name ${CONTAINER_NAME} ${DOCKER_IMAGE} $@
    docker rm ${CONTAINER_NAME} > /dev/null
}

case $1 in
    -h|--help)
        usage
        ;;
    -i|--init)
        __init
        ;;
    -u|--update)
        __update
        ;;
    *)
        main $@
        ;;
esac        